import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth,onAuthStateChanged,signOut } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { getFirestore,doc,setDoc,deleteDoc,updateDoc,collection,query,where,onSnapshot,getDocs,serverTimestamp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyAH8Lt8pnV000AHrmtjI3f-q1i71l3VYFU",authDomain:"course-racer.firebaseapp.com",projectId:"course-racer",storageBucket:"course-racer.firebasestorage.app",messagingSenderId:"491085898550",appId:"1:491085898550:web:7d5c266f7dba3dec074997"};
const ADMIN_UID="RcpTC3K2OpM5MfJDoNhOZhAx0K93",COURSE_ID="pup01x";const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let users=new Map(),pending=[],uc,up,cc;
const $=id=>document.getElementById(id);$("logoutBtn").onclick=()=>signOut(auth);$("closeLightbox").onclick=closeBox;$('lightbox').onclick=e=>{if(e.target.id==='lightbox')closeBox()};
onAuthStateChanged(auth,async u=>{if(!u){location.href='index.html';return}if(u.uid!==ADMIN_UID){$('denied').classList.remove('hidden');return}$('dashboard').classList.remove('hidden');await setDoc(doc(db,'courses',COURSE_ID),{locked:false},{merge:true});listen()});
function listen(){cc=onSnapshot(doc(db,'courses',COURSE_ID),s=>{let c=s.exists()?s.data():{};$('courseStatus').textContent=c.locked?'Locked':'Open';$('winnerStatus').textContent=c.winnerName?`🏆 Winner: ${c.winnerName} (${c.winnerScore} pts)`:'No winner declared.';$('declareWinnerBtn').disabled=!!c.locked});uc=onSnapshot(collection(db,'users'),s=>{users=new Map(s.docs.map(d=>[d.id,{id:d.id,...d.data()}]));$('racerCount').textContent=[...users.values()].filter(u=>u.id!==ADMIN_UID&&(u.role||'racer')==='racer').length;renderUsers()});up=onSnapshot(query(collection(db,'claims'),where('courseId','==',COURSE_ID),where('verified','==',null)),s=>{pending=s.docs.map(d=>({id:d.id,...d.data()}));$('pendingCount').textContent=pending.length;renderClaims()},e=>msg('Could not load submissions: '+e.message))}
function renderClaims(){if(!pending.length){$('claims').innerHTML='<div class="empty">No pending submissions.</div>';return}$('claims').innerHTML=pending.map(c=>{let u=users.get(c.uid);return `<article class="claim"><div class="claim-top"><div><b>${esc(u?.name||'Racer')}</b><div class="small">${esc(c.label)}</div></div><span class="pill">${c.type==='final'?`${c.percentage}% → ${c.points} pts`:'+4 pts'}</span></div><img src="${c.evidence}" data-img="${c.evidence}" alt="Evidence screenshot"><div class="claim-actions"><button data-a="${c.id}">✓ Approve</button><button class="danger" data-r="${c.id}">Reject</button></div></article>`}).join('');document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>review(b.dataset.a,true));document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>review(b.dataset.r,false));document.querySelectorAll('[data-img]').forEach(i=>i.onclick=()=>openBox(i.dataset.img))}
async function review(id,ok){try{let s=await getDocSafe(id);if(s?.locked)return;await updateDoc(doc(db,'claims',id),{verified:ok,verifiedAt:serverTimestamp(),verifiedBy:auth.currentUser.uid})}catch(e){msg('Review failed: '+e.message)}}
async function getDocSafe(id){const s=await getDocs(query(collection(db,'claims'),where('__name__','==',id)));return s.empty?null:s.docs[0].data()}
async function renderUsers(){let rs=[...users.values()].filter(u=>u.id!==ADMIN_UID&&(u.role||'racer')==='racer');if(!rs.length){$('users').innerHTML='<div class="empty">No racers yet.</div>';return}$('users').innerHTML=rs.map(u=>`<div class="user-row"><div><b>${esc(u.name||'Racer')}</b><div class="small">${esc(u.email||'')} · UID ${esc(u.id)}</div></div><button class="outline-danger" data-remove="${u.id}">Remove racer data</button></div>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeRacer(b.dataset.remove))}
async function removeRacer(uid){let u=users.get(uid);if(!u||!confirm(`Remove ${u.name||'this racer'} and all of their Course Racer data?`))return;try{let s=await getDocs(query(collection(db,'claims'),where('uid','==',uid)));for(let d of s.docs)await deleteDoc(d.ref);await deleteDoc(doc(db,'users',uid));msg(`${u.name||'Racer'} removed. Delete their Authentication account separately in Firebase Console if desired.`)}catch(e){msg('Removal failed: '+e.message)}}
$('declareWinnerBtn').onclick=async()=>{let rs=[...users.values()].filter(u=>u.id!==ADMIN_UID&&(u.role||'racer')==='racer'),rows=[];for(let u of rs){let s=await getDocs(query(collection(db,'claims'),where('uid','==',u.id),where('courseId','==',COURSE_ID),where('verified','==',true)));let a=s.docs.map(d=>d.data()),units=new Set(a.filter(c=>c.type==='unit').map(c=>c.itemKey)).size,finals=a.filter(c=>c.type==='final').reduce((n,c)=>n+Number(c.points||0),0);rows.push({...u,score:units*4+finals})}rows.sort((a,b)=>b.score-a.score||String(a.name).localeCompare(String(b.name)));let w=rows[0];if(!w)return alert('There are no racers.');if(!confirm(`Declare ${w.name} the winner with ${w.score} points and lock the course?`))return;await setDoc(doc(db,'courses',COURSE_ID),{winnerUid:w.id,winnerName:w.name,winnerScore:w.score,declaredAt:serverTimestamp(),declaredBy:auth.currentUser.uid,locked:true},{merge:true})};
function msg(s){$('adminMsg').textContent=s;setTimeout(()=>$('adminMsg').textContent='',6000)}function openBox(s){$('lightboxImg').src=s;$('lightbox').classList.remove('hidden')}function closeBox(){$('lightbox').classList.add('hidden');$('lightboxImg').src=''}function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
